package com.kms.grupo02

rule "Nada"
	when
		$j : Jugada (picas==0, fijas==0)
	then
        $j.actualizarEstado($j.getDigitoUno(), 0, Casilla.DESCARTADO);
        $j.actualizarPuntaje($j.getDigitoUno(), 0, 0);   
        $j.actualizarEstado($j.getDigitoUno(), 1, Casilla.DESCARTADO);
        $j.actualizarPuntaje($j.getDigitoUno(), 1, 0);  
        $j.actualizarEstado($j.getDigitoDos(), 0, Casilla.DESCARTADO);
        $j.actualizarPuntaje($j.getDigitoDos(), 0, 0);
        $j.actualizarEstado($j.getDigitoDos(), 1, Casilla.DESCARTADO);
        $j.actualizarPuntaje($j.getDigitoDos(), 1, 0);     
end


rule "Una pica"
	when
		$j : Jugada (picas==1, fijas==0)
	then
        $j.actualizarEstado($j.getDigitoUno(), 0, Casilla.DESCARTADO);
        $j.actualizarPuntaje($j.getDigitoUno(), 0, 0);   
        $j.actualizarEstado($j.getDigitoUno(), 1, Casilla.PICA);
        $j.actualizarPuntaje($j.getDigitoUno(), 1, 9);  
        $j.actualizarEstado($j.getDigitoDos(), 0, Casilla.PICA);
        $j.actualizarPuntaje($j.getDigitoDos(), 0, 9);
        $j.actualizarEstado($j.getDigitoDos(), 1, Casilla.DESCARTADO);
        $j.actualizarPuntaje($j.getDigitoDos(), 1, 0);  
end


rule "Una fija"
	when
		$j : Jugada (picas==0, fijas==1)
	then
        $j.actualizarEstado($j.getDigitoUno(), 0, Casilla.PICA_FIJA);
        $j.actualizarPuntaje($j.getDigitoUno(), 0, 9);   
        $j.actualizarEstado($j.getDigitoUno(), 1, Casilla.DESCARTADO);
        $j.actualizarPuntaje($j.getDigitoUno(), 1, 0);  
        $j.actualizarEstado($j.getDigitoDos(), 0, Casilla.DESCARTADO);
        $j.actualizarPuntaje($j.getDigitoDos(), 0, 0);
        $j.actualizarEstado($j.getDigitoDos(), 1, Casilla.PICA_FIJA);
        $j.actualizarPuntaje($j.getDigitoDos(), 1, 9);  
end